#!/bin/bash
type tui 2> /dev/zero || exit 1
. tui
releasever=19
config=sea-awesome.ks
title="AwesomeWM-F$releasever"
filename="sea-$title"

tui-title "Make $filename.iso"

cd
sudo livecd-creator -c $config --releasever=$releasever --title $title -f $filename
tui-status $? "Created sea-$title"
sudo chown $USER:$USER $filename.iso


tui-printf "Please insert an USB-stick"
tui-str-usb 2&> $TUI_TEMP_DIR/usb
usb=$(cat $TUI_TEMP_DIR/usb)

tui-title "Write it to: $usb"
sudo tui-dd $filename.iso $usb
