#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
License:	GPLv3, on scripts and kickstart files used to create the iso.
Created:	2013.09.02
Changed:	2014.08.31
Author: 	Simon A. Erat, erat.simon@gmail.com


Changed defaults for new users
------------------------------
Effected:
	* XDG_XY_DIRS
	* PS1


Default XDG dirs gives you this new structure:
----------------------------------------------
$HOME/
  + data/
  + mm/ 	(pics, snd, vids)
  + net/	(dls, fas, pub, web)
  + notepad	"former desktop"
  + priv/	(cloud, docs, templates)
  + prjs/

According to this, there have been placed links in ~/.gtk-bookmarks
Mounts: /mnt
Notepad: $HOME/notepad
Multimedia: $HOME/media
Internet: $HOME/net
Personal: $HOME/priv


New shell prompt PS1
--------------------
The new PS1 will look like (human-readable-syntax):	Returned_Value    Full_Path    Prompt_Symbol

Where Prompt_Symbol is
* '$' (white bg, blue font) for users
* '#' (red bg, white font) for root.

Where Returned_Value is:
* For successfull shellcommands, the prompt will display either one of: '+' ':)' '✔', colored green bg
* For failed shellcommands, the prompt will display either one of: '-' ':(' '✘', colored red bg
* Other exit status' will be reported by number, colored white bg
